---

- hosts: all
  gather_facts: false

  tasks:
    - include: "{{ item }}"
      with_fileglob:
        - "./playbooks/*.yml"
        - "./playbooks/software/*.yml"
        - "./playbooks/langs/*.yml"
