- name: Install asdf package manager
  homebrew:
    name: asdf

- name: Install asdf plugins
  asdf:
    plugin: "{{ item }}"
  with_items:
    - deno
    - helm
    - java
    - kubebuilder
    - kubectl
    - nodejs
    - operator-sdk
    - rust
    - terraform
    - yarn
    - golang
