- name: Install git
  homebrew: name=git

- name: Install hub
  homebrew: name=hub

- name: Install Git Extras
  homebrew: name=git-extras

- name: Install Git Lfs
  homebrew: name=git-lfs

- name: Link gitconfig
  file:
    src: "{{ playbook_dir }}/../files/gitconfig"
    dest: ~/.gitconfig
    state: link
    force: true
  tags: dotfiles

- name: Link gitexcludes
  file:
    src: "{{ playbook_dir }}/../files/gitexcludes"
    dest: ~/.gitexcludes
    state: link
    force: true
  tags: dotfiles
