# Update can break Input Source changing via Left and Right CMD
# 
# - name: Install Karabiner Elements
#   homebrew_cask:
#     name: karabiner-elements

- name: Link karabiner config
  file:
    src: "{{ playbook_dir }}/../files/karabiner.json"
    dest: ~/.config/karabiner/karabiner.json
    state: link
    force: true
