- name: Enable key repeat
  osx_defaults:
    key: ApplePressAndHoldEnabled
    type: boolean
    value: "false"

- name: Reduce key repeat time
  osx_defaults:
    key: KeyRepeat
    type: float
    value: "3.0"

- name: Reduce initial key repeat time
  osx_defaults:
    key: InitialKeyRepeat
    type: float
    value: "15.0"

- name: Enable text substitution in web apps (for example, Slack)
  osx_defaults:
    key: WebAutomaticTextReplacementEnabled
    type: bool
    value: "true"
