- name: Install fish
  homebrew:
    name: fish

- name: Create ~/.config/ folder
  file:
    path: ~/.config/
    state: directory

- name: Link .config/fish
  file:
    src: "{{ playbook_dir }}/../files/fish"
    dest: ~/.config/fish
    state: link
    force: true

- name: Set default shell to fish
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
  tags:
    - require_password

- name: Install Autojump
  homebrew:
    name: autojump
