- name: Install Neovim
  homebrew: name=neovim
  when: ansible_os_family == 'Darwin'

- name: Install Neovim
  apt: name=neovim
  when: ansible_os_family == 'Debian'
  become: yes

- name: Create directory for config
  file:
    path: ~/.config/nvim/
    state: directory

- name: Link neovim config
  file:
    src: "{{ playbook_dir }}/files/nvimrc"
    path: ~/.config/nvim/init.vim
    state: link
    force: true

- name: Create autoload directory
  file:
    path: ~/.config/nvim/autoload/
    state: directory

- name: Install vim-plug
  get_url:
    dest: ~/.config/nvim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
