- name: Install VSCodium
  homebrew_cask:
    name: vscodium

- name: Create folder for vscode settings
  file:
    path: "~/Library/Application\ Support/Code/User/"
    state: directory

- name: Link vscode settings
  file:
    src: "{{ playbook_dir }}/../files/vscode/settings.json"
    dest: "~/Library/Application\ Support/Code/User/settings.json"
    state: link
    force: true

- name: Link vscode keybindings
  file:
    src: "{{ playbook_dir }}/../files/vscode/keybindings.json"
    dest: "~/Library/Application\ Support/Code/User/keybindings.json"
    state: link
    force: true

- name: Create folder for vscode snippets
  file:
    path: "~/Library/Application\ Support/Code/User/snippets"
    state: directory

- name: Link vscode snippets
  file:
    src: "{{ playbook_dir }}/../files/vscode/snippets.json"
    path: "~/Library/Application\ Support/Code/User/snippets/{{ file }}"
    state: link
    force: true
  with_items:
    - javascript.json
    - javascriptreact.json
    - typescript.json
    - typescriptreact.json
  loop_control:
    loop_var: file

- name: Install VSCode extensions
  vscode:
    executable: codium
    extensions:
      - akamud.vscode-theme-onedark
      - asvetliakov.vscode-neovim
      - bmalehorn.vscode-fish
      - dbaeumer.vscode-eslint
      - denoland.vscode-deno
      - DotJoshJohnson.xml
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      - esbenp.prettier-vscode
      - esbenp.prettier-vscode
      - foxundermoon.shell-format
      - golang.go
      - hashicorp.terraform
      - heptio.jsonnet
      - janjoerke.jenkins-pipeline-linter-connector
      - me-dutour-mathieu.vscode-github-actions
      - mgmcdermott.vscode-language-babel
      - mrmlnc.vscode-stylefmt
      - ms-azuretools.vscode-docker
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - msjsdiag.debugger-for-chrome
      - QassimFarid.ejs-language-support
      - redhat.java
      - redhat.vscode-yaml
      - richie5um2.vscode-sort-json
      - rust-lang.rust
      - silvenon.mdx
      - tsandall.opa
      - vscodevim.vim
      - vscoss.vscode-ansible
      - WakaTime.vscode-wakatime
      - WallabyJs.quokka-vscode
      - william-voyek.vscode-nginx
      - xrc-inc.jsonnet-formatter
