let mapleader = ','

call plug#begin('~/.vim/plugged')
" linter
Plug 'neomake/neomake'
let g:neomake_javascript_eslint_exe = $PWD .'/node_modules/.bin/eslint'
let g:neomake_javascript_enabled_makers = ['eslint', 'flow']
autocmd! BufWritePost * Neomake

" file manager
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
nmap <leader><leader> :NERDTreeToggle<CR>

" Syntax highligthing
" javascript
Plug 'neovim/node-host', { 'do': 'npm install' }
Plug 'billyvg/tigris.nvim', { 'do': './install.sh' }

" Add smart commands for comments like:
" gcc - Toggle comment for the current line
" gc  - Toggle comments for selected region or number of strings
" Very usefull
Plug 'tomtom/tcomment_vim'

call plug#end()

" Reload config
nmap R :source $MYVIMRC<CR>

set expandtab
set shiftwidth=2
