let mapleader = ','

call plug#begin('~/.vim/plugged')
" -- Linters
Plug 'neomake/neomake'
let g:neomake_javascript_eslint_exe = $PWD .'/node_modules/.bin/eslint'
let g:neomake_javascript_enabled_makers = ['eslint', 'flow']
autocmd! BufWritePost * Neomake

" File manager
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
nmap <leader><leader> :NERDTreeToggle<CR>

" -- Syntax highligthing
" javascript
Plug 'neovim/node-host', { 'do': 'npm install' }
Plug 'billyvg/tigris.nvim', { 'do': './install.sh' }
let g:tigris#enabled = 1

" Add smart commands for comments like:
" gcc - Toggle comment for the current line
" gc  - Toggle comments for selected region or number of strings
" Very usefull
Plug 'tomtom/tcomment_vim'

" -- colors

Plug 'joshdick/onedark.vim'
set background=dark
let g:onedark_terminal_italics = 1

call plug#end()

" Reload config
nmap R :source $MYVIMRC<CR>

" Map arrows
imap <C-f> <Right>
imap <C-b> <Left>

set relativenumber
set expandtab
set shiftwidth=2
colorscheme onedark

" -- Persistent Undo
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo')
  silent !mkdir ~/.config/nvim/backups > /dev/null 2>&1
  set undodir=~/.config/nvim/backups
  set undofile
endif
