# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(osx, yarn, git)

source $ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# use λ instead of ➜ in prompt
local ret_status=" %(?:%{$fg_bold[green]%}λ:%{$fg_bold[red]%}λ %s)"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

RPS1="$(node -v)"

set -o vi
tabs -2 # set tab size to 2 spaces

# for substring search
bindkey '^P' up-line-or-search
bindkey '^N' down-line-or-search

bindkey '^F' autosuggest-accept

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source ~/.config/aliases
