- name: Install VS Code
  homebrew_cask: name=visual-studio-code

- name: Create folder for vscode settings
  file:
    path: "~/Library/Application\ Support/Code/User/"
    state: directory

- name: Link vscode settings
  file:
    src: "{{ playbook_dir }}/../files/vscode/settings.json"
    dest: "~/Library/Application\ Support/Code/User/settings.json"
    state: link
    force: true

- name: Link vscode keybindings
  file:
    src: "{{ playbook_dir }}/../files/vscode/keybindings.json"
    dest: "~/Library/Application\ Support/Code/User/keybindings.json"
    state: link
    force: true

- name: Create folder for vscode snippets
  file:
    path: "~/Library/Application\ Support/Code/User/snippets"
    state: directory

- name: Link vscode snippets
  file:
    src: "{{ playbook_dir }}/../files/vscode/snippets.json"
    path: "~/Library/Application\ Support/Code/User/snippets/{{ file }}"
    state: link
    force: true
  with_items:
    - javascript.json
    - javascriptreact.json
    - typescript.json
    - typescriptreact.json
  loop_control:
    loop_var: file

- name: Install VSCode extensions
  vscode:
    extensions:
      - EditorConfig.EditorConfig
      - Orta.vscode-jest
      - QassimFarid.ejs-language-support
      - WakaTime.vscode-wakatime
      - abierbaum.vscode-file-peek
      - akamud.vscode-theme-onedark
      - dbaeumer.vscode-eslint
      - eg2.tslint
      - ionutvmi.path-autocomplete
      - mrmlnc.vscode-duplicate
      - mrmlnc.vscode-stylefmt
      - msjsdiag.debugger-for-chrome
      - gcazaciuc.vscode-flow-ide
      - shinnn.stylelint
      - vscodevim.vim
      - waderyan.gitblame
      - tomhultonharrop.switch-corresponding # switch between js/css, h/cpp files
      - mgmcdermott.vscode-language-babel
      - eamodio.gitlens
      - pflannery.vscode-versionlens
