- name: Install VS Code
  homebrew_cask: name=visual-studio-code

- name: Create folder for vscode settings
  file:
    path: "~/Library/Application\ Support/Code/User/"
    state: directory

- name: Link vscode settings
  file:
    src: "{{ playbook_dir }}/files/vscode/settings.json"
    dest: "~/Library/Application\ Support/Code/User/settings.json"
    state: link
    force: true

- name: Link vscode keybindings
  file:
    src: "{{ playbook_dir }}/files/vscode/keybindings.json"
    dest: "~/Library/Application\ Support/Code/User/keybindings.json"
    state: link
    force: true

- name: Create folder for vscode snippets
  file:
    path: "~/Library/Application\ Support/Code/User/snippets"
    state: directory

- name: Link vscode snippets
  file:
    src: "{{ playbook_dir }}/files/vscode/snippets.json"
    path: "~/Library/Application\ Support/Code/User/snippets/{{ item }}"
    state: link
    force: true
  with_items:
    - javascript.json
    - javascriptreact.json
    - typescript.json
    - typescriptreact.json

- name: Install VSCode extensions
  vscode:
    extensions:
      - EditorConfig.EditorConfig
      - Orta.vscode-jest
      - PeterJausovec.vscode-docker
      - QassimFarid.ejs-language-support
      - WakaTime.vscode-wakatime
      - abierbaum.vscode-file-peek
      - akamud.vscode-theme-onedark
      - dbaeumer.vscode-eslint
      - eg2.tslint
      - henriiik.vscode-sort
      - hoovercj.vscode-ghc-mod
      - ionutvmi.path-autocomplete
      - joshjg.vscode-credo
      - justusadam.language-haskell
      - mjmcloug.vscode-elixir
      - mrmlnc.vscode-duplicate
      - mrmlnc.vscode-stylefmt
      - msjsdiag.debugger-for-chrome
      - rtorr.vscode-flow
      - shinnn.stylelint
      - vscodevim.vim
      - waderyan.gitblame
