- name: Install git
  homebrew: name=git state=present

- name: Link gitconfig
  file:
    src: "{{ playbook_dir }}/files/gitconfig"
    dest: ~/.gitconfig
    state: link
    force: true
  tags: dotfiles

- name: Link gitexcludes
  file:
    src: "{{ playbook_dir }}/files/gitexcludes"
    dest: ~/.gitexcludes
    state: link
    force: true
  tags: dotfiles
